version: '3'
services:
  database:
    image: mysql:8.0.17
    command: 
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: makersite
    volumes:
      - ..\storage\docker\makersite-mysql-data:/var/lib/mysql
    ports:
      - 3308:3306
  web_app:
    build: .
    volumes:
      - ./app:/var/www/
    ports:
      - 5001:80
    depends_on:
      - database